[package]
name = "tui"
version = "0.1.0"
edition = "2024"

[dependencies]
api = { version = "0.1.0", path = "../api" }
html2md = "0.2.15"
ratatui = "0.30.0"
tokio = { version = "1.49.0", features = ["full"] }
